# Generated by Django 4.2.11 on 2026-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('약품명', models.CharField(max_length=200, verbose_name='약품명')),
                ('성분명', models.CharField(max_length=200, verbose_name='성분명')),
                ('효능', models.TextField(verbose_name='효능')),
                ('용량', models.CharField(max_length=100, verbose_name='용량')),
                ('주의사항', models.TextField(verbose_name='주의사항')),
                ('회사명', models.CharField(max_length=200, verbose_name='회사명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '의약품',
                'verbose_name_plural': '의약품',
                'ordering': ['-created_at'],
            },
        ),
    ]
